//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 02:55:57 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/skupstina", 
									elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
								    xmlns={
								            @XmlNs(namespaceURI = "http://www.w3.org/ns/rdfa#", prefix = "rdf"),
								            @XmlNs(namespaceURI = "http://www.ftn.uns.ac.rs/skupstina/pred", prefix = "pred"),
								            @XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema#", prefix = "xsi")
								    })
package model.akt;

import javax.xml.bind.annotation.XmlNs;
