//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 07:36:42 PM CEST 
//


package model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.skupstina package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Stav_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Stav");
    private final static QName _Tacka_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Tacka");
    private final static QName _Podtacka_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Podtacka");
    private final static QName _Alineja_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Alineja");
    private final static QName _Preambula_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Preambula");
    private final static QName _Naslov_QNAME = new QName("http://www.ftn.uns.ac.rs/skupstina", "Naslov");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.skupstina
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link StavType }
     * 
     */
    public StavType createStavType() {
        return new StavType();
    }

    /**
     * Create an instance of {@link Odeljak }
     * 
     */
    public Odeljak createOdeljak() {
        return new Odeljak();
    }

    /**
     * Create an instance of {@link Pododeljak }
     * 
     */
    public Pododeljak createPododeljak() {
        return new Pododeljak();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link Glava }
     * 
     */
    public Glava createGlava() {
        return new Glava();
    }

    /**
     * Create an instance of {@link PodtackaType }
     * 
     */
    public PodtackaType createPodtackaType() {
        return new PodtackaType();
    }

    /**
     * Create an instance of {@link TackaType }
     * 
     */
    public TackaType createTackaType() {
        return new TackaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Stav")
    public JAXBElement<String> createStav(String value) {
        return new JAXBElement<String>(_Stav_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Tacka")
    public JAXBElement<String> createTacka(String value) {
        return new JAXBElement<String>(_Tacka_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Podtacka")
    public JAXBElement<String> createPodtacka(String value) {
        return new JAXBElement<String>(_Podtacka_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Alineja")
    public JAXBElement<String> createAlineja(String value) {
        return new JAXBElement<String>(_Alineja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Preambula")
    public JAXBElement<Object> createPreambula(Object value) {
        return new JAXBElement<Object>(_Preambula_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/skupstina", name = "Naslov")
    public JAXBElement<Object> createNaslov(Object value) {
        return new JAXBElement<Object>(_Naslov_QNAME, Object.class, null, value);
    }

}
